node {
    properties([
        pipelineTriggers([pollSCM('H/2 * * * *')]),
        disableConcurrentBuilds()
    ])

    stage('1') {
        echo "Run before get source"
    }

    stage('Get Source') {
        checkout([
           poll: false,
           $class: 'GitSCM',
           branches: [[name: '*/master']],
           doGenerateSubmoduleConfigurations: false,
           extensions: [
               [$class: 'DisableRemotePoll'],
               [$class: 'CleanBeforeCheckout'],
               [$class: 'PathRestriction', excludedRegions: '', includedRegions: 'frontend/.*']],
               submoduleCfg: [],
               userRemoteConfigs: [[credentialsId: 'mykola-github-key', url: "git@github.com:mshenhera/test-jenkins-pipeline.git"]]
       ])
    }

    stage('2') {
        echo "Run after get source"
    }
}
